import type { RatingWeights } from "@/lib/scoring";

export const defaultWeights: RatingWeights = {
  story: 5,
  direction: 5,
  writing: 5,
  acting: 5,
  music: 2,
  impact: 4,
  rewatchability: 10,
  rewatchabilityOffset: -50,
  genreFit: 3,
  divisor: 334,
};

export const defaultRubric = [
  { score: 10, meaning: "The perfect film", examples: [] },
  {
    score: 9,
    meaning: "Exceptional; among the best of its kind",
    examples: [],
  },
  { score: 8, meaning: "Excellent and easy to recommend", examples: [] },
  { score: 7, meaning: "Very good, with memorable strengths", examples: [] },
  { score: 6, meaning: "Good, despite noticeable limitations", examples: [] },
  { score: 5, meaning: "The average film", examples: [] },
  {
    score: 4,
    meaning: "Below average, with more misses than hits",
    examples: [],
  },
  {
    score: 3,
    meaning: "Poor, but with a few redeeming qualities",
    examples: [],
  },
  { score: 2, meaning: "Very poor and difficult to recommend", examples: [] },
  { score: 1, meaning: "Nearly without merit", examples: [] },
  { score: 0, meaning: "Neil Breen territory", examples: [] },
];

export const starterRcaTags = [
  ["story", "Compelling premise", "positive"],
  ["story", "Strong character arc", "positive"],
  ["story", "Predictable plotting", "negative"],
  ["story", "Weak third act", "negative"],
  ["direction", "Confident visual language", "positive"],
  ["direction", "Excellent pacing", "positive"],
  ["direction", "Uneven tone", "negative"],
  ["direction", "Flat staging", "negative"],
  ["writing", "Sharp dialogue", "positive"],
  ["writing", "Rich subtext", "positive"],
  ["writing", "Heavy exposition", "negative"],
  ["writing", "Thin characterization", "negative"],
  ["acting", "Standout lead", "positive"],
  ["acting", "Strong ensemble", "positive"],
  ["acting", "Uneven performances", "negative"],
  ["acting", "Miscast role", "negative"],
  ["music", "Memorable score", "positive"],
  ["music", "Great needle drops", "positive"],
  ["music", "Overbearing score", "negative"],
  ["music", "Forgettable soundtrack", "negative"],
  ["impact", "Emotionally resonant", "positive"],
  ["impact", "Thought-provoking", "positive"],
  ["impact", "Emotionally distant", "negative"],
  ["impact", "Limited staying power", "negative"],
  ["rewatchability", "Rewards repeat viewing", "positive"],
  ["rewatchability", "Comfort watch", "positive"],
  ["rewatchability", "Too exhausting", "negative"],
  ["rewatchability", "Little left to discover", "negative"],
  ["genre_fit", "Elevates the genre", "positive"],
  ["genre_fit", "Delivers genre thrills", "positive"],
  ["genre_fit", "Genre identity is muddled", "negative"],
  ["genre_fit", "Relies on genre clichés", "negative"],
  ["overall", "Instant favorite", "positive"],
  ["overall", "Easy recommendation", "positive"],
  ["overall", "More admirable than enjoyable", "neutral"],
  ["overall", "Missed potential", "negative"],
] as const;
